### PR TITLE
1、support labelText change

### PR DESCRIPTION
**Pull request by fengdianxun**
2、set TriLabelView have only one label awayls

### CODE REVIEW

**Comment by mukeshthawani** [comment]
Label text change support is already there and it's working fine.

**Comment by fengdianxun** [comment]
It have bug when each row have different text,for example No.1,No2,NO3...
Label text can not be reset text,When cell be reused,It still show the previous.

**Comment by mukeshthawani** [comment]
I tried that with different text for each row in a collection view and it is working fine.

**Comment by fengdianxun** [comment]
I am sorry,I did not express clearly.So I wrote a demo in "findbug" branch,storyboard mode.
[demo](https://github.com/fengdianxun/TriLabelView/tree/findbug)

**Comment by mukeshthawani** [comment]
Yeah, you are right I tried this use case. I will merge this PR. 👍

**Pull request merged**
